(function(root){
'use strict';
const SUITS=['♠','♥','♣','♦'];
function randomInt(n){if(!Number.isInteger(n)||n<1||n>4294967296)throw Error('Invalid random range');const a=new Uint32Array(1),limit=Math.floor(4294967296/n)*n;do{globalThis.crypto.getRandomValues(a)}while(a[0]>=limit);return a[0]%n;}
function deck(){const d=[];for(const s of SUITS)for(let rank=2;rank<=14;rank++)d.push({rank,suit:s});for(let i=d.length-1;i>0;i--){const j=randomInt(i+1);[d[i],d[j]]=[d[j],d[i]]}return d;}
function blackjackScore(hand){let score=hand.reduce((n,c)=>n+(c.rank===14?11:Math.min(c.rank,10)),0),aces=hand.filter(c=>c.rank===14).length;while(score>21&&aces-->0)score-=10;return score;}
function blackjackResult(player,dealer){const p=blackjackScore(player),d=blackjackScore(dealer);if(p>21)return {multiplier:0,label:'You went over 21'};const pn=p===21&&player.length===2,dn=d===21&&dealer.length===2;if(pn&&dn)return {multiplier:1,label:'Push. Two blackjacks'};if(dn)return {multiplier:0,label:'Dealer blackjack'};if(pn)return {multiplier:2.5,label:'Blackjack. Beautifully played'};if(d>21)return {multiplier:2,label:'Dealer busts. You win'};if(p>d)return {multiplier:2,label:'You win'};if(p===d)return {multiplier:1,label:'Push. Bet returned'};return {multiplier:0,label:'Dealer wins'};}
const paytable=[['Royal flush',800],['Straight flush',50],['Four of a kind',25],['Full house',9],['Flush',6],['Straight',4],['Three of a kind',3],['Two pair',2],['Jacks or better',1]];
function pokerResult(hand){if(hand.length!==5)throw Error('Five cards required');const ranks=hand.map(c=>c.rank).sort((a,b)=>a-b),counts={};ranks.forEach(r=>counts[r]=(counts[r]||0)+1);const groups=Object.values(counts).sort((a,b)=>b-a),flush=hand.every(c=>c.suit===hand[0].suit),straight=new Set(ranks).size===5&&(ranks[4]-ranks[0]===4||ranks.join(',')==='2,3,4,5,14');let index=-1;if(straight&&flush)index=ranks[0]===10?0:1;else if(groups[0]===4)index=2;else if(groups[0]===3&&groups[1]===2)index=3;else if(flush)index=4;else if(straight)index=5;else if(groups[0]===3)index=6;else if(groups[0]===2&&groups[1]===2)index=7;else if(Object.keys(counts).some(r=>counts[r]===2&&Number(r)>=11))index=8;return index===-1?{label:'No paying hand',multiplier:0}:{label:paytable[index][0],multiplier:paytable[index][1]};}
const red=[1,3,5,7,9,12,14,16,18,19,21,23,25,27,30,32,34,36];
const wheel=[0,32,15,19,4,21,2,25,17,34,6,27,13,36,11,30,8,23,10,5,24,16,33,1,20,14,31,9,22,18,29,7,28,12,35,3,26];
function rouletteResult(n,choice){if(!Number.isInteger(n)||n<0||n>36)throw Error('Invalid pocket');let win=false,multiplier=2;if(/^n\d+$/.test(choice)){const selected=Number(choice.slice(1));if(selected>36)throw Error('Invalid bet');win=n===selected;multiplier=36;}else if(!['red','black','odd','even','low','high'].includes(choice))throw Error('Invalid bet');else if(n!==0)win=choice==='red'?red.includes(n):choice==='black'?!red.includes(n):choice==='odd'?n%2===1:choice==='even'?n%2===0:choice==='low'?n<=18:n>=19;return {multiplier:win?multiplier:0,label:win?'Winning spin':'No winning bet this spin'};}
function validBet(value,balance){return Number.isInteger(value)&&value>=10&&value<=5000&&value<=balance;}
const api={deck,randomInt,blackjackScore,blackjackResult,pokerResult,paytable,red,wheel,rouletteResult,validBet};root.MonarchCore=api;if(typeof module!=='undefined')module.exports=api;
})(globalThis);
